#! /bin/sh

sxhkd &

#xrandr --output HDMI-0 --rotate left
#xrandr --output HDMI-0 --left-of DP-2
#xrandr --output DP-2 --primary

#~/.screenlayout/dual.sh
#start_from=1
#monitors_connected=$(bspc query -M | wc -l)
#per_monitor=$(( 10 / monitors_connected ))
#for monitor in $(bspc query -M); do
   #bspc monitor $monitor -d $(seq $start_from $(( start_from + per_monitor - 1)))
   #start_from=$(( start_from + per_monitor ))
#done

bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

nitrogen --set-zoom-fill ~/Pictures/bg1.png

~/.config/polybar/launch.sh --colorblocks

sudo gpro-led -a ffffff

picom &
